### PR TITLE
added quiz and final score

### PR DESCRIPTION
**Pull request by ashishkatiyar2404**
Screenshot (837)
Screenshot (836)
Screenshot (835)

### CODE REVIEW

**Review by varun1233 — APPROVED** [review]
Code looks good to merge

**Review by j24m — APPROVED** [review]
Did not find anything in code that needs changes, infact class names are pretty good, UI looks nice, Keep it up :)

**Review by kushalsourav — APPROVED** [review]
code is clean , looks good

**Comment by AagmanSuri** [comment]
code look neat and clean

**Pull request merged**
